name: Compile Certik

# Controls when the action will run.
#  This workflow runr on pushes to master & every Pull Requests. (Or when manually triggered)
on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

# This workflow makes x86_64 binaries for mac, windows, and linux.
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64]
        targetos: [darwin, linux]
        include:
          - targetos: darwin
            arch: arm64
#        include:
#          - targetos: windows
#            arch: amd64
    name: certik ${{ matrix.arch }} for ${{ matrix.targetos }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3.3.0
        with:
          go-version: '^1.18'
        env:
          GOOS: ${{ matrix.targetos }}
          GOARCH: ${{ matrix.arch }}

      - name: Compile certik binary
        run: |
          go mod download
          cd app/certik/cmd
          go build .

      - uses: actions/upload-artifact@v3
        with:
          name: certik ${{ matrix.targetos }} ${{ matrix.arch }}
          path: app/certik/cmd/certik
