name: Fmt
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  gofmt:
    name: gofmt
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Check code formatting using gofmt
      uses: Jerome1337/gofmt-action@v1.0.5