# This is a basic workflow that is manually triggered

name: State Sync

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [workflow_dispatch]

# This workflow tests state sync against the Notional archive server.
# To decentralize this workflow, add additional nodes to scripts/statesync.sh

jobs:
  build:
    runs-on: ubuntu-latest
    name: certik state sync
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3.3.0
        with:
          go-version: '^1.18'

      - name: state sync
        run: bash devtools/statesync.sh
